apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      labels:
        app: main-server
    spec:
      containers:
      - name: main-server
        image: gcr.io/GKE_PROJECT/IMAGE:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m